title: 'Course Number: Course Name'
description: 'Course Website (Template) for Course Number: Course Name by Course Instructor at Course Institution'
theme: just-the-docs

just_the_docs:
  math:
    provider: katex

url: https://

aux_links:
  External Link 1: https://www.google.com
  External Link 2: https://www.google.com
  Professor Bingxin Zhao: https://www.bingxinzhao.com